module.exports = {
  'apartmentlist.com': {
    'source': 'Apartment List',
    'City': 'city',
    'Community_Name': 'community_name',
    'PMC_Name': 'management company',
    'Paid_Backfill': 'apartmentlist rentals paid/unpaid',
    'Property_ID': 'apartmentlist property id',
    'State': 'state',
    'Street': 'street address',
    'URL': 'url',
    'Zip': 'zip code'
  },
  'forrent.com': {
    'source': 'ForRent',
    'Property Name': 'property name',
    'Unit_Count': 'unit count',
    'ForRent Paid/UnPaid': 'forrent paid/unpaid',
    'ForRent Package': 'forrent package',
    'City': 'city',
    'PMC_Name': 'management company',
    'Property_ID': 'forrent property id',
    'State': 'state',
    'Street': 'street address',
    'URL': 'url',
    'Zip': 'zip code'
  },
  'trulia.com': {
    'source': 'Trulia',
    'Community_Name': 'property name',
    'Unit_Count': 'unit count',
    'Trulia Rentals Paid/Unpaid': 'trulia rentals paid/unpaid',
    'Trulia Rentals Package': 'trulia rentals package',
    'City': 'city',
    'PMC_Name': 'management company',
    'Property_ID': 'trulia rentals property id',
    'State': 'state',
    'Street': 'street address',
    'URL': 'url',
    'Zip': 'zip code'
  },
  'zillow.com': {
    'source': 'Zillow',
    'Community_Name': 'property name',
    'Unit_Count': 'unit count',
    'Paid_Backfill': 'zillow rentals paid/unpaid',
    'Package': 'zillow rentals package',
    'City': 'city',
    'PMC_Name': 'management company',
    'Property_ID': 'zillow rentals property id',
    'State': 'state',
    'Street': 'street address',
    'URL': 'url',
    'Zip': 'zip code'
  },
  'apartments.com': {
    'source': 'Apartments',
    'Community_Name': 'property name',
    'Unit_Count': 'unit count',
    'Paid_Backfill': 'apartments paid/unpaid',
    'Package': 'apartments package',
    'City': 'city',
    'PMC_Name': 'management company',
    'Property_ID': 'apartments property id',
    'State': 'state',
    'Street': 'street address',
    'URL': 'url',
    'Zip': 'zip code'
  },
  'zumper.com': {
    'source': 'Zumper',
    'Community_Name': 'property name',
    'Unit_Count': 'unit count',
    'Paid_Backfill': 'zumper rentals paid/unpaid',
    'Package': 'zumper rentals package',
    'City': 'city',
    'PMC_Name': 'management company',
    'Property_ID': 'zumper rentals property id',
    'State': 'state',
    'Street': 'street address',
    'URL': 'url',
    'Zip': 'zip code'
  },
  'apartmentfinder.com': {
    'source': 'ApartmentFinder',
    'Community_Name': 'property name',
    'Unit_Count': 'unit count',
    'Paid_Backfill': 'apartmentfinder paid/unpaid',
    'Package': 'apartmentfinder package',
    'City': 'city',
    'PMC_Name': 'management company',
    'Property_ID': 'apartmentfinder property id',
    'State': 'state',
    'Street': 'street address',
    'URL': 'url',
    'Zip': 'zip code'
  }
};
