module.exports = {
  'trulia.com': {
    "source": "Trulia",
    "URL": "url",
    "Property_ID": "property_id",
    "PMC_Name": "pmc_name",
    "Package": "package",
    "Community_Name": "community_name",
    "Street": "street",
    "City": "city",
    "State": "state",
    "Zip": "zip",
    "Unit_Count": "unit_count",
    "Beds": "beds",
    "Baths": "baths",
    "Sq Ft": "sq ft",
    "Rent": "rent",
    "Photo_Count": "photo_count",
    "Paid_Backfill": "paid_backfill",
    "Reviews_Count": "reviews_count",
    "Reviews_<1 Mo": "reviews_<1 mo",
    "Reviews_1-3 Mo": "reviews_1-3 mo",
    "Reviews_4-6 Mo": "reviews_4-6 mo",
    "Reviews_7-11 Mo": "reviews_7-11 mo",
    "Reviews_1 Yr": "reviews_1 yr",
    "Reviews_2 Yr": "reviews_2 yr",
    "Reviews_3 Yr": "reviews_3 yr",
    "Reviews_4+ Yr": "reviews_4+ yr",
    "Reviews_Google": "reviews_google",
    "Reviews_Yelp": "reviews_yelp",
    "Reviews_Facebook": "reviews_facebook",
    "Reviews_Kudzu": "reviews_kudzu",
    "Reviews_Superpages": "reviews_superpages",
    "Reviews_Apartments": "reviews_apartments.com",
    "Reviews_With_Responses": "reviews_with_responses",
    "Ratings": "ratings",
    "Ratings_count": "ratings_count",
    "Property Description": "property description",
    "OneTime_Expense": "onetime_expense",
    "Assigned Garage Parking": "assigned garage parking",
    "Cat Rent": "cat rent",
    "Dog Rent": "dog rent",
    "Recurring_Expense": "recurring_expense",
    "Admin Fee": "admin fee",
    "Application Fee": "application fee",
    "Cat Fee": "cat fee",
    "Dog Fee": "dog fee",
    "Utilities Included": "utilities included",
    "Office_Hours": "office_hours",
    "Pet_Policy": "pet_policy",
    "Parking": "parking",
    "Availability - Date": "availability - date",
    "Availability - Available Now": "availability - available now",
    "Availability - Available Soon": "availability - available soon",
    "Availability - Check Availability": "availability - check availability",
    "Units_Available": "units_available",
    "Lease_Length": "lease_length",
    "Rent_Specials": "rent_specials",
    "ContactForm": "contactform",
    "Contact/Check Availability Link": "contact/check availability link",
    "Property_Information": "property_information",
    "Services": "services",
    "Fitness_Recreation": "fitness_recreation",
    "Features": "features",
    "Unique_Features": "unique_features",
    "Kitchen": "kitchen",
    "Living_Space": "living_space",
    "Interior": "interior",
    "Outdoor_Space": "outdoor_space",
    "Special_Features": "special_features",
    "Community_Features": "community_features",
    "FloorPlan_Amenities": "floorplan_amenities",
    "Property_Highlights": "property_highlights",
    "Apartment_Amenities": "apartment_amenities",
    "Amenities - Unit": "amenities - unit",
    "Amenities - Building": "amenities - building",
    "Unit Features": "unit features",
    "Building Amenities": "building amenities",
    "Special Amenities": "special amenities",
    "Rental Facts": "rental facts",
    "Construction": "construction",
    "Exterior Features": "exterior features",
    "Other": "other",
    "Unit": "unit",
    "Community": "community",
    "3D Tour": "3d tour",
    "Video Tour": "video tour",
    "Verified Tag:  CoStar Verified": "verified tag: costar verified",
    "Verified Tag:  Avoid Scams": "verified tag: avoid scams",
    "Verified Source": "verified source",
    "Property Deposit": "property deposit",
    "Pet Deposit": "pet deposit",
    "Schools": "schools",
    "Neighborhood": "neighborhood",
    "Neighborhood Overview": "neighborhood overview",
    "What Locals Say": "what locals say",
    "Affordability": "affordability",
    "Provided By": "provided by",
    "Property Website": "property website",
    "Property Phone #": "property phone #",
    "Property Stories": "property stories",
    "Year Built": "year built",
    "FloorPlan_Image": "floorplan_image",
    "Public_Transportation": "public_transportation",
    "Nearby_Transit_POI": "nearby_transit_poi",
    "Nearby_Apartments/Homes for Rent": "nearby_apartments/homes for rent",
    "Nearby Apartments/Homes for Rent Count": "nearby apartments/homes for rent count",
    "You may also like/Other Available Apartments": "you may also like/other available apartments",
    "You may also like/Other Available Apartments Count": "you may also like/other available apartments count",
    "Similar Rentals Nearby": "similar rentals nearby",
    "Similar Rentals Nearby Count": "similar rentals nearby count",
    "Explore more homes - Apartment Communities (Count)": "explore more homes - apartment communities (count)",
    "Explore more homes - Best Value (Count)": "explore more homes - best value (count)",
    "Walk Score": "walk score",
    "Transit Score": "transit score",
    "Sound Score": "sound score",
    "Crime Card": "crime card",
    "School Card": "school card",
    "Demographics Card": "demographics card",
    "Commute Card": "commute card",
    "Tour this place": "tour this place",
    "Rent Trends": "rent trends",
    "Longitude": "longitude",
    "Latitude": "latitude",
    "sale property": "Sale Property"
  },
  'apartments.com': {
    "source": "Apartments",
    "URL": "url",
    "Property_ID": "property_id",
    "PMC_Name": "pmc_name",
    "Package": "package",
    "Community_Name": "community_name",
    "Street": "street",
    "City": "city",
    "State": "state",
    "Zip": "zip",
    "Unit_Count": "unit_count",
    "Beds": "beds",
    "Baths": "baths",
    "Sq Ft": "sq ft",
    "Rent": "rent",
    "Photo_Count": "photo_count",
    "Paid_Backfill": "paid_backfill",
    "Reviews_Count": "reviews_count",
    "Reviews_<1 Mo": "reviews_<1 mo",
    "Reviews_1-3 Mo": "reviews_1-3 mo",
    "Reviews_3-6 Mo": "reviews_4-6 mo",
    "Reviews_6-11 Mo": "reviews_7-11 mo",
    "Reviews_1 Yr": "reviews_1 yr",
    "Reviews_2 Yr": "reviews_2 yr",
    "Reviews_3 Yr": "reviews_3 yr",
    "Reviews_4+ Y": "reviews_4+ yr",
    "Reviews_Google": "reviews_google",
    "Reviews_Yelp": "reviews_yelp",
    "Reviews_Facebook": "reviews_facebook",
    "Reviews_Kudzu": "reviews_kudzu",
    "Reviews_Superpages": "reviews_superpages",
    "Reviews_Apartments.com": "reviews_apartments.com",
    "Reviews_With_Responses": "reviews_with_responses",
    "Ratings": "ratings",
    "Ratings_count": "ratings_count",
    "Property Description": "property description",
    "OneTime_Expense": "onetime_expense",
    "assigned garage parking": "Assigned Garage Parking",
    "Cat Rent": "cat rent",
    "Dog Rent": "dog rent",
    "Recurring_Expense": "recurring_expense",
    "Admin Fee": "admin fee",
    "Application Fee": "application fee",
    "Cat Fee": "cat fee",
    "Dog Fee": "dog fee",
    "Utilities Included": "utilities included",
    "Office_Hours": "office_hours",
    "Pet_Policy": "pet_policy",
    "Parking": "parking",
    "Availability - Date": "availability - date",
    "Availability - Available Now": "availability - available now",
    "Availability - Available Soon": "availability - available soon",
    "Availability - Check Availability": "availability - check availability",
    "availability - none of these are available": "Availability - None of these are available",
    "Availability - Not Available": "availability - not available",
    "": "availability - no available units",
    "": "availability - no availability",
    "Units_Available": "units_available",
    "Lease_Length": "lease_length",
    "Rent_Specials": "rent_specials",
    "ContactForm": "contactform",
    "Contact/Check Availability Link": "contact/check availability link",
    "Property_Information": "property_information",
    "Services": "services",
    "Fitness_Recreation": "fitness_recreation",
    "Features": "features",
    "Unique_Features": "unique_features",
    "Kitchen": "kitchen",
    "Living_Space": "living_space",
    "Interior": "interior",
    "Outdoor_Space": "outdoor_space",
    "Special_Features": "special_features",
    "Community_Features": "community_features",
    "FloorPlan_Amenities": "floorplan_amenities",
    "Property_Highlights": "property_highlights",
    "Apartment_Amenities": "apartment_amenities",
    "Amenities - Unit": "amenities - unit",
    "Amenities - Building": "amenities - building",
    "Unit Features": "unit features",
    "Building Amenities": "building amenities",
    "Special Amenities": "special amenities",
    "Rental Facts": "rental facts",
    "Construction": "construction",
    "Exterior Features": "exterior features",
    "Other": "other",
    "Unit": "unit",
    "Community": "community",
    "3D Tour": "3d tour",
    "Video Tour": "video tour",
    "Verified Tag: CoStar Verified": "verified tag: costar verified",
    "Verified Tag: Avoid Scams": "verified tag: avoid scams",
    "Verified Source": "verified source",
    "Deposit": "property deposit",
    "Pet Deposit": "pet deposit",
    "Schools": "schools",
    "Neighborhood": "neighborhood",
    "Neighborhood Overview": "neighborhood overview",
    "What Locals say": "what locals say",
    "Affordability": "affordability",
    "Provided By": "provided by",
    "Property Website": "property website",
    "Property Phone #": "property phone #",
    "Property Stories": "property stories",
    "Year Built": "year built",
    "FloorPlan_Image": "floorplan_image",
    "Public_Transportation": "public_transportation",
    "Nearby_Transit_POI": "nearby_transit_poi",
    "Nearby_Apartments/Homes for Rent": "nearby_apartments/homes for rent",
    "Nearby Apartments/Homes for Rent Count": "nearby apartments/homes for rent count",
    "You may also like/Other Available Apartments": "you may also like/other available apartments",
    "You may also like/Other Available Apartments Count": "you may also like/other available apartments count",
    "Similar Rentals Nearby": "similar rentals nearby",
    "Similar Rentals Nearby Count": "similar rentals nearby count",
    "Explore more homes - Apartment Communities (Count)": "explore more homes - apartment communities (count)",
    "Explore more homes - Best Value (Count)": "explore more homes - best value (count)",
    "Walk Score": "walk score",
    "Transit Score": "transit score",
    "Sound Score": "sound score",
    "Crime card": "crime card",
    "School card": "school card",
    "Demographics card": "demographics card",
    "Commute card": "commute card",
    "Tour this place": "tour this place",
    "Rent Trends": "rent trends",
    "Longitude": "longitude",
    "Latitude": "latitude"
  },
  'apartmentfinder.com': {
    "source": "Apartmentfinder.com",
    "URL": "url",
    "Property_ID": "property_id",
    "PMC_Name": "pmc_name",
    "Package": "package",
    "Community_Name": "community_name",
    "Street": "street",
    "City": "city",
    "State": "state",
    "Zip": "zip",
    "Unit_Count": "unit_count",
    "Beds": "beds",
    "Baths": "baths",
    "Sq Ft": "sq ft",
    "Rent": "rent",
    "Photo_Count": "photo_count",
    "Paid_Backfill": "paid_backfill",
    "Reviews_Count": "reviews_count",
    "Reviews_<1 Mo": "reviews_<1 mo",
    "Reviews_1-3 Mo": "reviews_1-3 mo",
    "Reviews_4-6 Mo": "reviews_4-6 mo",
    "Reviews_7-11 Mo": "reviews_7-11 mo",
    "Reviews_1 Yr": "reviews_1 yr",
    "Reviews_2 Yr": "reviews_2 yr",
    "Reviews_3 Yr": "reviews_3 yr",
    "Reviews_4+ Yr": "reviews_4+ yr",
    "Reviews_Google": "reviews_google",
    "Reviews_Yelp": "reviews_yelp",
    "Reviews_Facebook": "reviews_facebook",
    "Reviews_Kudzu": "reviews_kudzu",
    "Reviews_Superpages": "reviews_superpages",
    "Reviews_Apartments.com": "reviews_apartments.com",
    "Reviews_With_Responses": "reviews_with_responses",
    "Ratings": "ratings",
    "Ratings_count": "ratings_count",
    "Property Description": "property description",
    "OneTime_Expense": "onetime_expense",
    "Assigned Garage Parking": "assigned garage parking",
    "Cat Rent": "cat rent",
    "Dog Rent": "dog rent",
    "Recurring_Expense": "recurring_expense",
    "Admin Fee": "admin fee",
    "Application Fee": "application fee",
    "Cat Fee": "cat fee",
    "Dog Fee": "dog fee",
    "Utilities Included": "utilities included",
    "Office_Hours": "office_hours",
    "Pet_Policy": "pet_policy",
    "Parking": "parking",
    "Availability - Date": "availability - date",
    "Availability - Available Now": "availability - available now",
    "Availability - Available Soon": "availability - available soon",
    "Contact/Check Availability Link": "availability - check availability",
    "Availability - None of these are available": "availability - none of these are available",
    "Availability - Not Available": "availability - not available",
    "Availability - No Available units": "availability - no available units",
    "Availability - No Availability": "availability - no availability",
    "Units_Available": "units_available",
    "Lease_Length": "lease_length",
    "Rent_Specials": "rent_specials",
    "ContactForm": "contactform",
    "Property_Information": "property_information",
    "Services": "services",
    "Fitness_Recreation": "fitness_recreation",
    "Features": "features",
    "Unique_Features": "unique_features",
    "Kitchen": "kitchen",
    "Living_Space": "living_space",
    "Interior": "interior",
    "Outdoor_Space": "outdoor_space",
    "Special_Features": "special_features",
    "Community_Features": "community_features",
    "FloorPlan_Amenities": "floorplan_amenities",
    "Property_Highlights": "property_highlights",
    "Apartment_Amenities": "apartment_amenities",
    "Amenities - Unit": "amenities - unit",
    "Amenities - Building": "amenities - building",
    "Unit Features": "unit features",
    "Building Amenities": "building amenities",
    "Special Amenities": "special amenities",
    "Rental Facts": "rental facts",
    "Construction": "construction",
    "Exterior Features": "exterior features",
    "Other": "other",
    "Unit": "unit",
    "Community": "community",
    "3D Tour": "3d tour",
    "Video Tour": "video tour",
    "Verified Tag: CoStar Verified": "verified tag: costar verified",
    "Verified Tag: Avoid Scams": "verified tag: avoid scams",
    "Verified Source": "verified source",
    "Property Deposit": "property deposit",
    "Pet Deposit": "pet deposit",
    "Schools": "schools",
    "Neighborhood": "neighborhood",
    "Neighborhood Overview": "neighborhood overview",
    "What Locals say": "what locals say",
    "Affordability": "affordability",
    "Provided By": "provided by",
    "Property Website": "property website",
    "Property Phone #": "property phone #",
    "Property Stories": "property stories",
    "Year Built": "year built",
    "FloorPlan_Image": "floorplan_image",
    "Public_Transportation": "public_transportation",
    "Nearby_Transit_POI": "nearby_transit_poi",
    "Nearby_Apartments/Homes for Rent": "nearby_apartments/homes for rent",
    "Nearby Apartments/Homes for Rent Count": "nearby apartments/homes for rent count",
    "You may also like/Other Available Apartments": "you may also like/other available apartments",
    "You may also like/Other Available Apartments Count": "you may also like/other available apartments count",
    "Similar Rentals Nearby": "similar rentals nearby",
    "Similar Rentals Nearby Count": "similar rentals nearby count",
    "Explore more homes - Apartment Communities (Count)": "explore more homes - apartment communities (count)",
    "Explore more homes - Best Value (Count)": "explore more homes - best value (count)",
    "Walk Score": "walk score",
    "Transit Score": "transit score",
    "Sound Score": "sound score",
    "Crime card": "crime card",
    "School card": "school card",
    "Demographics card": "demographics card",
    "Commute card": "commute card",
    "Tour this place": "tour this place",
    "Rent Trends": "rent trends",
    "Longitude": "longitude",
    "Latitude": "latitude"
  },
  'forrent.com': {
    "source": "ForRent",
    "URL": "url",
    "Property_ID": "property_id",
    "PMC_Name": "pmc_name",
    "ForRent Package": "package",
    "Community_Name": "community_name",
    "Street": "street",
    "City": "city",
    "State": "state",
    "Zip": "zip",
    "Unit_Count": "unit_count",
    "Beds": "beds",
    "Baths": "baths",
    "Sq Ft": "sq ft",
    "Rent": "rent",
    "Photo_Count": "photo_count",
    "Paid_Backfill": "paid_backfill",
    "Reviews_Count": "reviews_count",
    "Reviews_<1 Mo": "reviews_<1 mo",
    "Reviews_1-3 Mo": "reviews_1-3 mo",
    "Reviews_4-6 Mo": "reviews_4-6 mo",
    "Reviews_7-11 Mo": "reviews_7-11 mo",
    "Reviews_1 Yr": "reviews_1 yr",
    "Reviews_2 Yr": "reviews_2 yr",
    "Reviews_3 Yr": "reviews_3 yr",
    "Reviews_4+ Yr": "reviews_4+ yr",
    "Reviews_Google": "reviews_google",
    "Reviews_Yelp": "reviews_yelp",
    "Reviews_Facebook": "reviews_facebook",
    "Reviews_Kudzu": "reviews_kudzu",
    "Reviews_Superpages": "reviews_superpages",
    "Reviews_Apartments.com": "reviews_apartments.com",
    "Reviews_With_Responses": "reviews_with_responses",
    "Ratings": "ratings",
    "Ratings_count": "ratings_count",
    "Property Description": "property description",
    "OneTime_Expense": "onetime_expense",
    "Assigned Garage Parking": "assigned garage parking",
    "Cat Rent": "cat rent",
    "Dog Rent": "dog rent",
    "Recurring_Expense": "recurring_expense",
    "Admin Fee": "admin fee",
    "Application Fee": "application fee",
    "Cat Fee": "cat fee",
    "Dog Fee": "dog fee",
    "Utilities Included": "utilities included",
    "Office_Hours": "office_hours",
    "Pet_Policy": "pet_policy",
    "Parking": "parking",
    "Availability - Date": "availability - date",
    "Availability - Available Now": "availability - available now",
    "Availability - Available Soon": "availability - available soon",
    "Availability - Check Availability": "availability - check availability",
    "Units_Available": "units_available",
    "Lease_Length": "lease_length",
    "Rent_Specials": "rent_specials",
    "ContactForm": "contactform",
    "Contact/Check Availability Link": "contact/check availability link",
    "Property_Information": "property_information",
    "Services": "services",
    "Fitness_Recreation": "fitness_recreation",
    "Features": "features",
    "Unique_Features": "unique_features",
    "Kitchen": "kitchen",
    "Living_Space": "living_space",
    "Interior": "interior",
    "Outdoor_Space": "outdoor_space",
    "Special_Features": "special_features",
    "Community_Features": "community_features",
    "FloorPlan_Amenities": "floorplan_amenities",
    "Property_Highlights": "property_highlights",
    "Apartment_Amenities": "apartment_amenities",
    "Amenities - Unit": "amenities - unit",
    "Amenities - Building": "amenities - building",
    "Unit Features": "unit features",
    "Building Amenities": "building amenities",
    "Special Amenities": "special amenities",
    "Rental Facts": "rental facts",
    "Construction": "construction",
    "Exterior Features": "exterior features",
    "Other": "other",
    "Unit": "unit",
    "Community": "community",
    "3D Tour": "3d tour",
    "Video Tour": "video tour",
    "Verified Tag: CoStar Verified": "verified tag: costar verified",
    "Verified Tag: Avoid Scams": "verified tag: avoid scams",
    "Verified Source": "verified source",
    "Property Deposit": "property deposit",
    "Pet Deposit": "pet deposit",
    "Schools": "schools",
    "Neighborhood": "neighborhood",
    "Neighborhood Overview": "neighborhood overview",
    "What Locals say": "what locals say",
    "Affordability": "affordability",
    "Provided By": "provided by",
    "Property Website": "property website",
    "Property Phone #": "property phone #",
    "Property Stories": "property stories",
    "Year Built": "year built",
    "FloorPlan_Image": "floorplan_image",
    "Public_Transportation": "public_transportation",
    "Nearby_Transit_POI": "nearby_transit_poi",
    "Nearby_Apartments/Homes for Rent": "nearby_apartments/homes for rent",
    "Nearby Apartments/Homes for Rent Count": "nearby apartments/homes for rent count",
    "You may also like/Other Available Apartments": "you may also like/other available apartments",
    "You may also like/Other Available Apartments Count": "you may also like/other available apartments count",
    "Similar Rentals Nearby": "similar rentals nearby",
    "Similar Rentals Nearby Count": "similar rentals nearby count",
    "Explore more homes - Apartment Communities (Count)": "explore more homes - apartment communities (count)",
    "Explore more homes - Best Value (Count)": "explore more homes - best value (count)",
    "Walk Score": "walk score",
    "Transit Score": "transit score",
    "Sound Score": "sound score",
    "Crime card": "crime card",
    "School card": "school card",
    "Demographics card": "demographics card",
    "Commute card": "commute card",
    "Tour this place": "tour this place",
    "Rent Trends": "rent trends",
    "Longitude": "longitude",
    "Latitude": "latitude"
  },
  'zumper.com': {
    "source": "Zumper",
    "URL": "url",
    "Property_ID": "property_id",
    "PMC_Name": "pmc_name",
    "Package": "package",
    "Community_Name": "community_name",
    "Street": "street",
    "City": "city",
    "State": "state",
    "Zip": "zip",
    "Unit_Count": "unit_count",
    "Beds": "beds",
    "Baths": "baths",
    "Sq Ft": "sq ft",
    "Rent": "rent",
    "Photo_Count": "photo_count",
    "Paid_Backfill": "paid_backfill",
    "Reviews_Count": "reviews_count",
    "Reviews_<1 Mo": "reviews_<1 mo",
    "Reviews_1-3 Mo": "reviews_1-3 mo",
    "Reviews_3-6 Mo": "reviews_4-6 mo",
    "Reviews_6-11 Mo": "reviews_7-11 mo",
    "Reviews_1 Yr": "reviews_1 yr",
    "Reviews_2 Yr": "reviews_2 yr",
    "Reviews_3 Yr": "reviews_3 yr",
    "Reviews_4+ Yr": "reviews_4+ yr",
    "Reviews_Google": "reviews_google",
    "Reviews_Yelp": "reviews_yelp",
    "Reviews_Facebook": "reviews_facebook",
    "Reviews_Kudzu": "reviews_kudzu",
    "Reviews_Superpages": "reviews_superpages",
    "Reviews_Apartments.com": "reviews_apartments.com",
    "Reviews_With_Responses": "reviews_with_responses",
    "Ratings": "ratings",
    "Ratings_count": "ratings_count",
    "Property Description": "property description",
    "OneTime_Expense": "onetime_expense",
    "Assigned Garage Parking": "assigned garage parking",
    "Cat Rent": "cat rent",
    "Dog Rent": "dog rent",
    "Recurring_Expense": "recurring_expense",
    "Admin Fee": "admin fee",
    "Application Fee": "application fee",
    "Cat Fee": "cat fee",
    "Dog Fee": "dog fee",
    "Utilities Included": "utilities included",
    "Office_Hours": "office_hours",
    "Pet_Policy": "pet_policy",
    "Parking": "parking",
    "Availability - Date": "availability - date",
    "Availability - Available Now": "availability - available now",
    "Availability - Available Soon": "availability - available soon",
    "Availability - Check Availability": "availability - check availability",
    "Units_Available": "units_available",
    "Lease_Length": "lease_length",
    "Rent_Specials": "rent_specials",
    "ContactForm": "contactform",
    "Contact/Check Availability Link": "contact/check availability link",
    "Property_Information": "property_information",
    "Services": "services",
    "Fitness_Recreation": "fitness_recreation",
    "Features": "features",
    "Unique_Features": "unique_features",
    "Kitchen": "kitchen",
    "Living_Space": "living_space",
    "Interior": "interior",
    "Outdoor_Space": "outdoor_space",
    "Special_Features": "special_features",
    "Community_Features": "community_features",
    "FloorPlan_Amenities": "floorplan_amenities",
    "Property_Highlights": "property_highlights",
    "Apartment_Amenities": "apartment_amenities",
    "Amenities - Unit": "amenities - unit",
    "Amenities - Building": "amenities - building",
    "Unit Features": "unit features",
    "Building Amenities": "building amenities",
    "Special Amenities": "special amenities",
    "Rental Facts": "rental facts",
    "Construction": "construction",
    "Exterior Features": "exterior features",
    "Other": "other",
    "Unit": "unit",
    "Community": "community",
    "3D Tour": "3d tour",
    "Verified Tag: CoStar Verified": "verified tag: costar verified",
    "Verified Tag: Avoid Scams": "verified tag: avoid scams",
    "Verified Source": "verified source",
    "Deposit": "property deposit",
    "Pet Deposit": "pet deposit",
    "Schools": "schools",
    "Neighborhood": "neighborhood",
    "Neighborhood Overview": "neighborhood overview",
    "What Locals say": "what locals say",
    "Affordability": "affordability",
    "Provided By": "provided by",
    "Property Website": "property website",
    "Property Phone #": "property phone #",
    "Property Stories": "property stories",
    "Year Built": "year built",
    "FloorPlan_Image": "floorplan_image",
    "Public_Transportation": "public_transportation",
    "Nearby_Transit_POI": "nearby_transit_poi",
    "Nearby_Apartments/Homes for Rent": "nearby_apartments/homes for rent",
    "Nearby Apartments/Homes for Rent Count": "nearby apartments/homes for rent count",
    "You may also like/Other Available Apartments": "you may also like/other available apartments",
    "You may also like/Other Available Apartments Count": "you may also like/other available apartments count",
    "Similar Rentals Nearby": "similar rentals nearby",
    "Similar Rentals Nearby Count": "similar rentals nearby count",
    "Explore more homes - Apartment Communities (Count)": "explore more homes - apartment communities (count)",
    "Explore more homes - Best Value (Count)": "explore more homes - best value (count)",
    "Walk Score": "walk score",
    "Transit Score": "transit score",
    "Sound Score": "sound score",
    "Crime card": "crime card",
    "School card": "school card",
    "Demographics card": "demographics card",
    "Commute card": "commute card",
    "Tour this place": "tour this place",
    "Rent Trends": "rent trends",
    "Longitude": "longitude",
    "Latitude": "latitude",
  },
  'zillow.com': {
    "source": "Zillow",
    "": "url",
    "Property_ID": "property_id",
    "PMC_Name": "pmc_name",
    "Package": "package",
    "Community_Name": "community_name",
    "Street": "street",
    "City": "city",
    "State": "state",
    "Zip": "zip",
    "Unit_Count": "unit_count",
    "Beds": "beds",
    "Baths": "baths",
    "Sqft": "sq ft",
    "Rent": "rent",
    "Photo_count": "photo_count",
    "Paid_Backfill": "paid_backfill",
    "Reviews_Count": "reviews_count",
    "Reviews_<1 Mo": "reviews_<1 mo",
    "Reviews_1-3 Mo": "reviews_1-3 mo",
    "Reviews_4-6 Mo": "reviews_4-6 mo",
    "Reviews_7-11 Mo": "reviews_7-11 mo",
    "Reviews_1 Yr": "reviews_1 yr",
    "Reviews_2 Yr": "reviews_2 yr",
    "Reviews_3 Yr": "reviews_3 yr",
    "Reviews_4+ Yr": "reviews_4+ yr",
    "Reviews_Google": "reviews_google",
    "Reviews_Yelp": "reviews_yelp",
    "Reviews_Facebook": "reviews_facebook",
    "Reviews_Kudzu": "reviews_kudzu",
    "Reviews_Superpages": "reviews_superpages",
    "Reviews_Apartments.com": "reviews_apartments.com",
    "Reviews_With_Responses": "reviews_with_responses",
    "Ratings": "ratings",
    "Ratings_count": "ratings_count",
    "Property Description": "property description",
    "OneTime_Expense": "onetime_expense",
    "Assigned Garage Parking": "assigned garage parking",
    "Cat Rent": "cat rent",
    "Dog Rent": "dog rent",
    "Recurring_Expense": "recurring_expense",
    "Admin Fee": "admin fee",
    "Application Fee": "application fee",
    "Cat Fee": "cat fee",
    "Dog Fee": "dog fee",
    "Utilities Included": "utilities included",
    "Office_Hours": "office_hours",
    "Pet Policy": "pet_policy",
    "Parking": "parking",
    "Availability - Date": "availability - date",
    "Availability - Available Now": "availability - available now",
    "Availability - Available Soon": "availability - available soon",
    "Availability - Check Availability": "availability - check availability",
    "Availability - None of these are available": "availability - none of these are available",
    "Availability - Not Available": "availability - not available",
    "Availability - No Available units": "availability - no available units",
    "Availability - No Availability": "availability - no availability",
    "Units_Available": "units_available",
    "Lease_Length": "lease_length",
    "Rent_Specials": "rent_specials",
    "ContactForm": "contactform",
    "Contact/Check Availability Link": "contact/check availability link",
    "Property_Information": "property_information",
    "Services": "services",
    "Fitness_Recreation": "fitness_recreation",
    "Features": "features",
    "Unique_Features": "unique_features",
    "Kitchen": "kitchen",
    "Living_Space": "living_space",
    "Interior": "interior",
    "Outdoor_Space": "outdoor_space",
    "Special_Features": "special_features",
    "Community_Features": "community_features",
    "FloorPlan_Amenities": "floorplan_amenities",
    "Property_Highlights": "property_highlights",
    "Apartment_Amenities": "apartment_amenities",
    "Amenities - Unit": "amenities - unit",
    "Amenities - Building": "amenities - building",
    "Unit Features": "unit features",
    "Building Amenities": "building amenities",
    "Special Amenities": "special amenities",
    "Rental Facts": "rental facts",
    "Construction": "construction",
    "Exterior Features": "exterior features",
    "Other": "other",
    "Unit": "unit",
    "Community": "community",
    "3D Tour": "3d tour",
    "Video Tour": "video tour",
    "Verified Tag: CoStar Verified": "verified tag: costar verified",
    "Verified Tag: Avoid Scams": "verified tag: avoid scams",
    "Verified Source": "verified source",
    "Property Deposit": "property deposit",
    "Pet Deposit": "pet deposit",
    "School": "schools",
    "Neighborhood": "neighborhood",
    "Neighborhood Overview": "neighborhood overview",
    "What Locals say": "what locals say",
    "Affordability": "affordability",
    "Provided By": "provided by",
    "Property Website": "property website",
    "Property Phone #": "property phone #",
    "Property Stories": "property stories",
    "Year Built": "year built",
    "FloorPlan_Image": "floorplan_image",
    "Public_Transportation": "public_transportation",
    "Nearby_Transit_POI": "nearby_transit_poi",
    "Nearby_Apartments/Homes for Rent": "nearby_apartments/homes for rent",
    "Nearby Apartments/Homes for Rent Count": "nearby apartments/homes for rent count",
    "You may also like/Other Available Apartments": "you may also like/other available apartments",
    "You may also like/Other Available Apartments Count": "you may also like/other available apartments count",
    "Similar Rentals Nearby": "similar rentals nearby",
    "Similar Rentals Nearby Count": "similar rentals nearby count",
    "Explore more homes - Apartment Communities (Count)": "explore more homes - apartment communities (count)",
    "Explore more homes - Best Value (Count)": "explore more homes - best value (count)",
    "Walk Score": "walk score",
    "Transit Score": "transit score",
    "Sound": "sound score",
    "Crime Card": "crime card",
    "School Card": "school card",
    "Demo Graphics Card": "demographics card",
    "Commute Card": "commute card",
    "Tour This Place": "tour this place",
    "Rent Trends": "rent trends",
    "Longitude": "longitude",
    "Latitude": "latitude",
    "Sale Property": "sale property"
  },
  'apartmentlist.com': {
    'source': 'Apartment List',
    'Admin Fee': 'admin fee',
    'Application Fee': 'application fee',
    'Availability - Available Now': 'availability - available now',
    'Availability - Available Soon': 'availability - available soon',
    'Availability - Check Availability': 'availability - check availability',
    'Availability - Date': 'availability - date',
    'Baths': 'baths',
    'Beds': 'beds',
    'Cat Fee': 'cat fee',
    'Cat Rent': 'cat rent',
    'City': 'city',
    'Community_Name': 'community_name',
    'Contact/Check Availability Link': 'contact/check availability link',
    'ContactForm': 'contactform',
    'Dog Fee': 'dog fee',
    'Dog Rent': 'dog rent',
    'Lease_Length': 'lease_length',
    'PMC_Name': 'pmc_name',
    'Parking': 'parking',
    'Pet Deposit': 'pet deposit',
    'Photo_Count': 'photo_count',
    'Property Description': 'property description',
    'Property_ID': 'property_id',
    'Rent': 'rent',
    'Rent_Specials': 'rent_specials',
    'Similar Rentals Nearby': 'similar rentals nearby',
    'Similar Rentals Nearby Count': 'similar rentals nearby count',
    'Sq Ft': 'sq ft',
    'State': 'state',
    'Street': 'street',
    'Transit Score': 'transit score',
    'URL': 'url',
    'Units_Available': 'units_available',
    'Zip': 'zip'
  }
};
