module.exports = {
  'apartmentlist.com': {
    'source': 'Apartment List',
    'Admin Fee': 'admin fee',
    'Application Fee': 'application fee',
    'Availability - Available Now': 'availability - available now',
    'Availability - Available Soon': 'availability - available soon',
    'Availability - Check Availability': 'availability - check availability',
    'Availability - Date': 'availability - date',
    'Baths': 'baths',
    'Beds': 'beds',
    'Cat Fee': 'cat fee',
    'Cat Rent': 'cat rent',
    'City': 'city',
    'Community_Name': 'community_name',
    'Contact/Check Availability Link': 'contact/check availability link',
    'ContactForm': 'contactform',
    'Dog Fee': 'dog fee',
    'Dog Rent': 'dog rent',
    'Lease_Length': 'lease_length',
    'PMC_Name': 'pmc_name',
    'Parking': 'parking',
    'Pet Deposit': 'pet deposit',
    'Photo_Count': 'photo_count',
    'Property Description': 'property description',
    'Property_ID': 'property_id',
    'Rent': 'rent',
    'Rent_Specials': 'rent_specials',
    'Similar Rentals Nearby': 'similar rentals nearby',
    'Similar Rentals Nearby Count': 'similar rentals nearby count',
    'Sq Ft': 'sq ft',
    'State': 'state',
    'Street': 'street',
    'Transit Score': 'transit score',
    'URL': 'url',
    'Units_Available': 'units_available',
    'Zip': 'zip'
  },
  'trulia.com': {
    'source': 'Trulia',
    'Admin Fee': 'admin fee',
    'Application Fee': 'application fee',
    'Availability - Available Now': 'availability - available now',
    'Availability - Available Soon': 'availability - available soon',
    'Availability - Check Availability': 'availability - check availability',
    'Availability - Date': 'availability - date',
    'Baths': 'baths',
    'Beds': 'beds',
    'Cat Fee': 'cat fee',
    'Cat Rent': 'cat rent',
    'City': 'city',
    'Community_Name': 'community_name',
    'Contact/Check Availability Link': 'contact/check availability link',
    'ContactForm': 'contactform',
    'Dog Fee': 'dog fee',
    'Dog Rent': 'dog rent',
    'Lease_Length': 'lease_length',
    'PMC_Name': 'pmc_name',
    'Parking': 'parking',
    'Pet Deposit': 'pet deposit',
    'Photo_Count': 'photo_count',
    'Property Description': 'property description',
    'Property_ID': 'property_id',
    'Rent': 'rent',
    'Rent_Specials': 'rent_specials',
    'Similar Rentals Nearby': 'similar rentals nearby',
    'Similar Rentals Nearby Count': 'similar rentals nearby count',
    'Sq Ft': 'sq ft',
    'State': 'state',
    'Street': 'street',
    'Transit Score': 'transit score',
    'URL': 'url',
    'Units_Available': 'units_available',
    'Zip': 'zip'
  }
};